MinGW: Fix a compile error due to a missing #include.
  In file included from [...]/pv/globalsettings.cpp:20:0:
  [...]/pv/globalsettings.hpp:31:12: error: 'std::function' has not been declared
   using std::function;
              ^
  test/CMakeFiles/pulseview-test.dir/build.make:88: recipe for target 'test/CMakeFiles/pulseview-test.dir/__/pv/globalsettings.cpp.obj' failed
  make[2]: *** [test/CMakeFiles/pulseview-test.dir/__/pv/globalsettings.cpp.obj] Error 1
  make[2]: *** Waiting for unfinished jobs....
  [  5%] Building CXX object CMakeFiles/pulseview.dir/pv/globalsettings.cpp.obj
  In file included from [...]/pv/globalsettings.cpp:20:0:
  [...]/pv/globalsettings.hpp:31:12: error: 'std::function' has not been declared
   using std::function;
              ^

Add #include <functional> everywhere where std::function is used. Only
the occurence in globalsettings.hpp was causing an actual build failure
on MinGW, though.