win32: Fix the Windows build (namespace pollution via windows.h).
One of the multiple build errors:

  In file included from [...]/windows.h:72:0,
                   from [...]/boost/detail/interlocked.hpp:27,
                   from [...]/boost/thread/win32/thread_primitives.hpp:18,
                   from [...]/boost/thread/win32/thread_data.hpp:11,
                   from [...]/boost/thread/thread_only.hpp:15,
                   from [...]/boost/thread/thread.hpp:12,
                   from [...]/boost/thread.hpp:13,
                   from [...]/pulseview/pv/session.hpp:32,
                   from [...]/pulseview/pv/devicemanager.cpp:22:
  [...]/libsigrok/enums.hpp:153:32: error: expected unqualified-id before numeric constant
    static const Quantity * const DIFFERENCE;
                                  ^

windows.h is included by boost/thread.hpp, hence the conflict can be avoided
by defining NOGDI and NORESOURCE before including thread.hpp.

This fixes bug #517.