tests/CMakeLists.txt: Add missing boost-thread check.
find_package(Boost ...) was missing the "thread" entry, which caused
linking to fail in some situations.

[100%] Building CXX object test/CMakeFiles/pulseview-test.dir/__/pv/widgets/moc_wellarray.cxx.o
Linking CXX executable pulseview-test
CMakeFiles/pulseview-test.dir/__/pv/sigsession.cpp.o: In function `pv::SigSession::SigSession(pv::DeviceManager&)':
sigsession.cpp:(.text+0xfa): undefined reference to `boost::thread::thread()'
[....]