Add missing newlines in two header files.
Without the newlines, some compilers will spew warnings such as:

  cursor.h:83:37: error: no newline at end of file

(which will break the build due to -Werror, which is default-enabled)

This has been (for example) observed on FreeBSD 9.0's (patched) gcc 4.2.1.