Declare a virtual destructor for SignalData
This fixes the following error:

error: deleting object of polymorphic class type 'pv::data::Analog'
which has non-virtual destructor might cause undefined behaviour
[-Werror=delete-non-virtual-dtor]

Also, the same error for pv::data::Logic.