pv/exprtk.hpp: Fix Windows build issues.
Define NOGDI and NORESOURCE in order to avoid unneeded namespace
pollution caused by <windows.h>, which leads to errors such as:

  libsigrokcxx/enums.hpp:374:36: error: expected unqualified-id before numeric constant
    static const QuantityFlag * const RELATIVE;
                                      ^

  libsigrokcxx/enums.hpp:161:32: error: expected unqualified-id before numeric constant
    static const Quantity * const DIFFERENCE;
                                  ^