Add missing <cmath> #includes.
Some compilers throw warnings/errors otherwise:

  error: no member named 'abs' in namespace 'std'; did you mean '::abs'?"