analogsignal.cpp: Fix std::isnan() related compile issue on some systems
Re-do for recent source what commit f9abacf20c85 did to solve bug #531.
Explicitly use std::isnan() in checks. Avoid the 'using' directive since
not all platforms that are supported by sigrok do support it.

  pv/views/trace/analogsignal.cpp:54:12: error: 'isnan' is already declared in this scope