MinGW: Fix a compile error due to missing std::isnan.
pv/view/viewport.cpp: In member function 'virtual void pv::view::Viewport::drag_by(const QPoint&)':
pv/view/viewport.cpp:85:24: error: 'isnan' was not declared in this scope
  if (isnan(drag_offset_))
                        ^
pv/view/viewport.cpp:85:24: note: suggested alternative:
In file included from pv/view/viewport.cpp:22:0:
[...]/usr/lib/gcc/i686-w64-mingw32.static/4.9.2/include/c++/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^