tests: Fix #include order.
<libsigrokdecode/libsigrokdecode.h> should be included first (as the
comment says), otherwise a warning can be the result (error in this
case due to -Werror usage):

[ 90%] Building CXX object test/CMakeFiles/pulseview-test.dir/data/decoder.cpp.o
In file included from /usr/include/python3.2mu/Python.h:8:0,
                 from [....]/include/libsigrokdecode/libsigrokdecode.h:25,
                 from [....]/test/data/decoder.cpp:23:
/usr/include/python3.2mu/pyconfig.h:1182:0: error: "_POSIX_C_SOURCE" redefined [-Werror]
 #define _POSIX_C_SOURCE 200112L
 ^