Fix two errors with clang 3.6.
[...]/pv/view/viewport.cpp:202:6: error: using integer absolute value
function 'abs' when argument is of floating point
type [-Werror,-Wabsolute-value]
        if (abs(w) >= 1.0) {
            ^
[...]/pv/view/viewport.cpp:202:6: note: use function 'std::abs' instead
        if (abs(w) >= 1.0) {
            ^~~
            std::abs

[...]/pv/widgets/sweeptimingwidget.cpp:172:33: error: absolute value
function 'abs' given an argument of type 'long' but has parameter of
type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
                const int64_t this_variance = abs(
                                              ^
[...]/pv/widgets/sweeptimingwidget.cpp:172:33: note: use function
'std::abs' instead
                const int64_t this_variance = abs(
                                              ^~~
                                              std::abs