samplingbar.cpp: Add missing "ULL".
10000000000 is too large for an int/long on 32bit systems, properly list it
as 10000000000ULL, otherwise the compile will fail.

samplingbar.cpp:48: error: integer constant is too large for 'long' type.